# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libshm', [dirname(__file__)])
        except ImportError:
            import _libshm
            return _libshm
        if fp is not None:
            try:
                _mod = imp.load_module('_libshm', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _libshm = swig_import_helper()
    del swig_import_helper
else:
    import _libshm
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


SHMSZ = _libshm.SHMSZ
SHMKEY = _libshm.SHMKEY
SHMRD = _libshm.SHMRD
SHMWD = _libshm.SHMWD
class VODPlayStat(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VODPlayStat, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VODPlayStat, name)
    __repr__ = _swig_repr
    __swig_setmethods__["position"] = _libshm.VODPlayStat_position_set
    __swig_getmethods__["position"] = _libshm.VODPlayStat_position_get
    if _newclass:position = _swig_property(_libshm.VODPlayStat_position_get, _libshm.VODPlayStat_position_set)
    __swig_setmethods__["length"] = _libshm.VODPlayStat_length_set
    __swig_getmethods__["length"] = _libshm.VODPlayStat_length_get
    if _newclass:length = _swig_property(_libshm.VODPlayStat_length_get, _libshm.VODPlayStat_length_set)
    __swig_setmethods__["status"] = _libshm.VODPlayStat_status_set
    __swig_getmethods__["status"] = _libshm.VODPlayStat_status_get
    if _newclass:status = _swig_property(_libshm.VODPlayStat_status_get, _libshm.VODPlayStat_status_set)
    def __init__(self): 
        this = _libshm.new_VODPlayStat()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libshm.delete_VODPlayStat
    __del__ = lambda self : None;
VODPlayStat_swigregister = _libshm.VODPlayStat_swigregister
VODPlayStat_swigregister(VODPlayStat)

class SimpleSharedMemory(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SimpleSharedMemory, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SimpleSharedMemory, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _libshm.new_SimpleSharedMemory()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _libshm.delete_SimpleSharedMemory
    __del__ = lambda self : None;
    def doConnect(self): return _libshm.SimpleSharedMemory_doConnect(self)
    def doClose(self): return _libshm.SimpleSharedMemory_doClose(self)
    def setStatus(self, *args): return _libshm.SimpleSharedMemory_setStatus(self, *args)
SimpleSharedMemory_swigregister = _libshm.SimpleSharedMemory_swigregister
SimpleSharedMemory_swigregister(SimpleSharedMemory)



