ISO3166 = [
	(_("Afghanistan"), "AF", "AFG"),
	(_("Aland Islands"), "AX", "ALA"),
	(_("Albania"), "AL", "ALB"),
	(_("Algeria"), "DZ", "DZA"),
	(_("American Samoa"), "AS", "ASM"),
	(_("Andorra"), "AD", "AND"),
	(_("Angola"), "AO", "AGO"),
	(_("Anguilla"), "AI", "AIA"),
	(_("Antarctica"), "AQ", "ATA"),
	(_("Antigua and Barbuda"), "AG", "ATG"),
	(_("Argentina"), "AR", "ARG"),
	(_("Armenia"), "AM", "ARM"),
	(_("Aruba"), "AW", "ABW"),
	(_("Australia"), "AU", "AUS"),
	(_("Austria"), "AT", "AUT"),
	(_("Azerbaijan"), "AZ", "AZE"),
	(_("Bahamas"), "BS", "BHS"),
	(_("Bahrain"), "BH", "BHR"),
	(_("Bangladesh"), "BD", "BGD"),
	(_("Barbados"), "BB", "BRB"),
	(_("Belarus"), "BY", "BLR"),
	(_("Belgium"), "BE", "BEL"),
	(_("Belize"), "BZ", "BLZ"),
	(_("Benin"), "BJ", "BEN"),
	(_("Bermuda"), "BM", "BMU"),
	(_("Bhutan"), "BT", "BTN"),
	(_("Bolivia (Plurinational State of)"), "BO", "BOL"),
	(_("Bonaire, Sint Eustatius and Saba"), "BQ", "BES"),
	(_("Bosnia and Herzegovina"), "BA", "BIH"),
	(_("Botswana"), "BW", "BWA"),
	(_("Bouvet Island"), "BV", "BVT"),
	(_("Brazil"), "BR", "BRA"),
	(_("British Indian Ocean Territory"), "IO", "IOT"),
	(_("Brunei Darussalam"), "BN", "BRN"),
	(_("Bulgaria"), "BG", "BGR"),
	(_("Burkina Faso"), "BF", "BFA"),
	(_("Burundi"), "BI", "BDI"),
	(_("Cabo Verde"), "CV", "CPV"),
	(_("Cambodia"), "KH", "KHM"),
	(_("Cameroon"), "CM", "CMR"),
	(_("Canada"), "CA", "CAN"),
	(_("Cayman Islands"), "KY", "CYM"),
	(_("Central African Republic"), "CF", "CAF"),
	(_("Chad"), "TD", "TCD"),
	(_("Chile"), "CL", "CHL"),
	(_("China"), "CN", "CHN"),
	(_("Christmas Island"), "CX", "CXR"),
	(_("Cocos (Keeling) Islands"), "CC", "CCK"),
	(_("Colombia"), "CO", "COL"),
	(_("Comoros"), "KM", "COM"),
	(_("Congo"), "CG", "COG"),
	(_("Congo (Democratic Republic of the)"), "CD", "COD"),
	(_("Cook Islands"), "CK", "COK"),
	(_("Costa Rica"), "CR", "CRI"),
	(_("Cote d'Ivoire"), "CI", "CIV"),
	(_("Croatia"), "HR", "HRV"),
	(_("Cuba"), "CU", "CUB"),
	(_("Curacao"), "CW", "CUW"),
	(_("Cyprus"), "CY", "CYP"),
	(_("Czechia"), "CZ", "CZE"),
	(_("Denmark"), "DK", "DNK"),
	(_("Djibouti"), "DJ", "DJI"),
	(_("Dominica"), "DM", "DMA"),
	(_("Dominican Republic"), "DO", "DOM"),
	(_("Ecuador"), "EC", "ECU"),
	(_("Egypt"), "EG", "EGY"),
	(_("El Salvador"), "SV", "SLV"),
	(_("Equatorial Guinea"), "GQ", "GNQ"),
	(_("Eritrea"), "ER", "ERI"),
	(_("Estonia"), "EE", "EST"),
	(_("Ethiopia"), "ET", "ETH"),
	(_("Falkland Islands (Malvinas)"), "FK", "FLK"),
	(_("Faroe Islands"), "FO", "FRO"),
	(_("Fiji"), "FJ", "FJI"),
	(_("Finland"), "FI", "FIN"),
	(_("France"), "FR", "FRA"),
	(_("French Guiana"), "GF", "GUF"),
	(_("French Polynesia"), "PF", "PYF"),
	(_("French Southern Territories"), "TF", "ATF"),
	(_("Gabon"), "GA", "GAB"),
	(_("Gambia"), "GM", "GMB"),
	(_("Georgia"), "GE", "GEO"),
	(_("Germany"), "DE", "DEU"),
	(_("Ghana"), "GH", "GHA"),
	(_("Gibraltar"), "GI", "GIB"),
	(_("Greece"), "GR", "GRC"),
	(_("Greenland"), "GL", "GRL"),
	(_("Grenada"), "GD", "GRD"),
	(_("Guadeloupe"), "GP", "GLP"),
	(_("Guam"), "GU", "GUM"),
	(_("Guatemala"), "GT", "GTM"),
	(_("Guernsey"), "GG", "GGY"),
	(_("Guinea"), "GN", "GIN"),
	(_("Guinea-Bissau"), "GW", "GNB"),
	(_("Guyana"), "GY", "GUY"),
	(_("Haiti"), "HT", "HTI"),
	(_("Heard Island and McDonald Islands"), "HM", "HMD"),
	(_("Holy See"), "VA", "VAT"),
	(_("Honduras"), "HN", "HND"),
	(_("Hong Kong"), "HK", "HKG"),
	(_("Hungary"), "HU", "HUN"),
	(_("Iceland"), "IS", "ISL"),
	(_("India"), "IN", "IND"),
	(_("Indonesia"), "ID", "IDN"),
	(_("Iran (Islamic Republic of)"), "IR", "IRN"),
	(_("Iraq"), "IQ", "IRQ"),
	(_("Ireland"), "IE", "IRL"),
	(_("Isle of Man"), "IM", "IMN"),
	(_("Israel"), "IL", "ISR"),
	(_("Italy"), "IT", "ITA"),
	(_("Jamaica"), "JM", "JAM"),
	(_("Japan"), "JP", "JPN"),
	(_("Jersey"), "JE", "JEY"),
	(_("Jordan"), "JO", "JOR"),
	(_("Kazakhstan"), "KZ", "KAZ"),
	(_("Kenya"), "KE", "KEN"),
	(_("Kiribati"), "KI", "KIR"),
	(_("Korea (Democratic People's Republic of)"), "KP", "PRK"),
	(_("Korea (Republic of)"), "KR", "KOR"),
	(_("Kuwait"), "KW", "KWT"),
	(_("Kyrgyzstan"), "KG", "KGZ"),
	(_("Lao People's Democratic Republic"), "LA", "LAO"),
	(_("Latvia"), "LV", "LVA"),
	(_("Lebanon"), "LB", "LBN"),
	(_("Lesotho"), "LS", "LSO"),
	(_("Liberia"), "LR", "LBR"),
	(_("Libya"), "LY", "LBY"),
	(_("Liechtenstein"), "LI", "LIE"),
	(_("Lithuania"), "LT", "LTU"),
	(_("Luxembourg"), "LU", "LUX"),
	(_("Macao"), "MO", "MAC"),
	(_("Macedonia (the former Yugoslav Republic of)"), "MK", "MKD"),
	(_("Madagascar"), "MG", "MDG"),
	(_("Malawi"), "MW", "MWI"),
	(_("Malaysia"), "MY", "MYS"),
	(_("Maldives"), "MV", "MDV"),
	(_("Mali"), "ML", "MLI"),
	(_("Malta"), "MT", "MLT"),
	(_("Marshall Islands"), "MH", "MHL"),
	(_("Martinique"), "MQ", "MTQ"),
	(_("Mauritania"), "MR", "MRT"),
	(_("Mauritius"), "MU", "MUS"),
	(_("Mayotte"), "YT", "MYT"),
	(_("Mexico"), "MX", "MEX"),
	(_("Micronesia (Federated States of)"), "FM", "FSM"),
	(_("Moldova (Republic of)"), "MD", "MDA"),
	(_("Monaco"), "MC", "MCO"),
	(_("Mongolia"), "MN", "MNG"),
	(_("Montenegro"), "ME", "MNE"),
	(_("Montserrat"), "MS", "MSR"),
	(_("Morocco"), "MA", "MAR"),
	(_("Mozambique"), "MZ", "MOZ"),
	(_("Myanmar"), "MM", "MMR"),
	(_("Namibia"), "NA", "NAM"),
	(_("Nauru"), "NR", "NRU"),
	(_("Nepal"), "NP", "NPL"),
	(_("Netherlands"), "NL", "NLD"),
	(_("New Caledonia"), "NC", "NCL"),
	(_("New Zealand"), "NZ", "NZL"),
	(_("Nicaragua"), "NI", "NIC"),
	(_("Niger"), "NE", "NER"),
	(_("Nigeria"), "NG", "NGA"),
	(_("Niue"), "NU", "NIU"),
	(_("Norfolk Island"), "NF", "NFK"),
	(_("Northern Mariana Islands"), "MP", "MNP"),
	(_("Norway"), "NO", "NOR"),
	(_("Oman"), "OM", "OMN"),
	(_("Pakistan"), "PK", "PAK"),
	(_("Palau"), "PW", "PLW"),
	(_("Palestine, State of"), "PS", "PSE"),
	(_("Panama"), "PA", "PAN"),
	(_("Papua New Guinea"), "PG", "PNG"),
	(_("Paraguay"), "PY", "PRY"),
	(_("Peru"), "PE", "PER"),
	(_("Philippines"), "PH", "PHL"),
	(_("Pitcairn"), "PN", "PCN"),
	(_("Poland"), "PL", "POL"),
	(_("Portugal"), "PT", "PRT"),
	(_("Puerto Rico"), "PR", "PRI"),
	(_("Qatar"), "QA", "QAT"),
	(_("Reunion"), "RE", "REU"),
	(_("Romania"), "RO", "ROU"),
	(_("Russian Federation"), "RU", "RUS"),
	(_("Rwanda"), "RW", "RWA"),
	(_("Saint Barthelemy"), "BL", "BLM"),
	(_("Saint Helena, Ascension and Tristan da Cunha"), "SH", "SHN"),
	(_("Saint Kitts and Nevis"), "KN", "KNA"),
	(_("Saint Lucia"), "LC", "LCA"),
	(_("Saint Martin (French part)"), "MF", "MAF"),
	(_("Saint Pierre and Miquelon"), "PM", "SPM"),
	(_("Saint Vincent and the Grenadines"), "VC", "VCT"),
	(_("Samoa"), "WS", "WSM"),
	(_("San Marino"), "SM", "SMR"),
	(_("Sao Tome and Principe"), "ST", "STP"),
	(_("Saudi Arabia"), "SA", "SAU"),
	(_("Senegal"), "SN", "SEN"),
	(_("Serbia"), "RS", "SRB"),
	(_("Seychelles"), "SC", "SYC"),
	(_("Sierra Leone"), "SL", "SLE"),
	(_("Singapore"), "SG", "SGP"),
	(_("Sint Maarten (Dutch part)"), "SX", "SXM"),
	(_("Slovakia"), "SK", "SVK"),
	(_("Slovenia"), "SI", "SVN"),
	(_("Solomon Islands"), "SB", "SLB"),
	(_("Somalia"), "SO", "SOM"),
	(_("South Africa"), "ZA", "ZAF"),
	(_("South Georgia and the South Sandwich Islands"), "GS", "SGS"),
	(_("South Sudan"), "SS", "SSD"),
	(_("Spain"), "ES", "ESP"),
	(_("Sri Lanka"), "LK", "LKA"),
	(_("Sudan"), "SD", "SDN"),
	(_("Suriname"), "SR", "SUR"),
	(_("Svalbard and Jan Mayen"), "SJ", "SJM"),
	(_("Swaziland"), "SZ", "SWZ"),
	(_("Sweden"), "SE", "SWE"),
	(_("Switzerland"), "CH", "CHE"),
	(_("Syrian Arab Republic"), "SY", "SYR"),
	(_("Taiwan"), "TW", "TWN"),
	(_("Tajikistan"), "TJ", "TJK"),
	(_("Tanzania, United Republic of"), "TZ", "TZA"),
	(_("Thailand"), "TH", "THA"),
	(_("Timor-Leste"), "TL", "TLS"),
	(_("Togo"), "TG", "TGO"),
	(_("Tokelau"), "TK", "TKL"),
	(_("Tonga"), "TO", "TON"),
	(_("Trinidad and Tobago"), "TT", "TTO"),
	(_("Tunisia"), "TN", "TUN"),
	(_("Turkey"), "TR", "TUR"),
	(_("Turkmenistan"), "TM", "TKM"),
	(_("Turks and Caicos Islands"), "TC", "TCA"),
	(_("Tuvalu"), "TV", "TUV"),
	(_("Uganda"), "UG", "UGA"),
	(_("Ukraine"), "UA", "UKR"),
	(_("United Arab Emirates"), "AE", "ARE"),
	(_("United Kingdom"), "GB", "GBR"),
	(_("United States of America"), "US", "USA"),
	(_("United States Minor Outlying Islands"), "UM", "UMI"),
	(_("Uruguay"), "UY", "URY"),
	(_("Uzbekistan"), "UZ", "UZB"),
	(_("Vanuatu"), "VU", "VUT"),
	(_("Venezuela (Bolivarian Republic of)"), "VE", "VEN"),
	(_("Viet Nam"), "VN", "VNM"),
	(_("Virgin Islands (British)"), "VG", "VGB"),
	(_("Virgin Islands (U.S.)"), "VI", "VIR"),
	(_("Wallis and Futuna"), "WF", "WLF"),
	(_("Western Sahara"), "EH", "ESH"),
	(_("Yemen"), "YE", "YEM"),
	(_("Zambia"), "ZM", "ZMB"),
	(_("Zimbabwe"), "ZW", "ZWE")
]
