# -*- coding: iso-8859-2 -*-
LanguageCodes = {"aar": ("Afar", "Hamitic"),
				 "aa": ("Afar", "Hamitic"),
				 "abk": ("Abkhazian", "Ibero-caucasian"),
				 "ab": ("Abkhazian", "Ibero-caucasian"),
				 "ace": ("Achinese", ""),
				 "ach": ("Acoli", ""),
				 "ada": ("Adangme", ""),
				 "afa": ("Afro-Asiatic (Other)", ""),
				 "afh": ("Afrihili", ""),
				 "afr": ("Afrikaans", "Germanic"),
				 "af": ("Afrikaans", "Germanic"),
				 "aka": ("Akan", ""),
				 "akk": ("Akkadian", ""),
				 "ale": ("Aleut", ""),
				 "alg": ("Algonquian languages", ""),
				 "amh": ("Amharic", "Semitic"),
				 "am": ("Amharic", "Semitic"),
				 "ang": ("English, Old (ca. 450-1100)", ""),
				 "apa": ("Apache languages", ""),
				 "ara": ("Arabic", "Semitic"),
				 "ar": ("Arabic", "Semitic"),
				 "arc": ("Aramaic", ""),
				 "arn": ("Araucanian", ""),
				 "arp": ("Arapaho", ""),
				 "art": ("Artificial (Other)", ""),
				 "arw": ("Arawak", ""),
				 "asm": ("Assamese", "Indian"),
				 "as": ("Assamese", "Indian"),
				 "ath": ("Athapascan languages", ""),
				 "aus": ("Australian languages", ""),
				 "ava": ("Avaric", ""),
				 "ave": ("Avestan", ""),
				 "ae": ("Avestan", ""),
				 "awa": ("Awadhi", ""),
				 "aym": ("Aymara", "Amerindian"),
				 "ay": ("Aymara", "Amerindian"),
				 "aze": ("Azerbaijani", "Turkic/altaic"),
				 "az": ("Azerbaijani", "Turkic/altaic"),
				 "bad": ("Banda", ""),
				 "bai": ("Bamileke languages", ""),
				 "bak": ("Bashkir", "Turkic/altaic"),
				 "ba": ("Bashkir", "Turkic/altaic"),
				 "bal": ("Baluchi", ""),
				 "bam": ("Bambara", ""),
				 "ban": ("Balinese", ""),
				 "bas": ("Basa", ""),
				 "bat": ("Baltic (Other)", ""),
				 "bej": ("Beja", ""),
				 "bel": ("Belarusian", "Slavic"),
				 "be": ("Belarusian", "Slavic"),
				 "bem": ("Bemba", ""),
				 "ben": ("Bengali", "Indian"),
				 "bn": ("Bengali", "Indian"),
				 "ber": ("Berber (Other)", ""),
				 "bho": ("Bhojpuri", ""),
				 "bih": ("Bihari", "Indian"),
				 "bh": ("Bihari", "Indian"),
				 "bik": ("Bikol", ""),
				 "bin": ("Bini", ""),
				 "bis": ("Bislama", ""),
				 "bi": ("Bislama", ""),
				 "bla": ("Siksika", ""),
				 "bnt": ("Bantu (Other)", ""),
				 "bod": ("Tibetan", "Asian"),
				 "tib": ("Tibetan", "Asian"),
				 "bo": ("Tibetan", "Asian"),
				 "bos": ("Bosnian", ""),
				 "bs": ("Bosnian", ""),
				 "bra": ("Braj", ""),
				 "bre": ("Breton", "Celtic"),
				 "br": ("Breton", "Celtic"),
				 "btk": ("Batak (Indonesia)", ""),
				 "bua": ("Buriat", ""),
				 "bug": ("Buginese", ""),
				 "bul": ("Bulgarian", "Slavic"),
				 "bg": ("Bulgarian", "Slavic"),
				 "cad": ("Caddo", ""),
				 "cai": ("Central American Indian (Other)", ""),
				 "car": ("Carib", ""),
				 "cat": ("Catalan", "Romance"),
				 "ca": ("Catalan", "Romance"),
				 "cau": ("Caucasian (Other)", ""),
				 "ceb": ("Cebuano", ""),
				 "cel": ("Celtic (Other)", ""),
				 "ces": ("Czech", "Slavic"),
				 "cze": ("Czech", "Slavic"),
				 "cs": ("Czech", "Slavic"),
				 "cha": ("Chamorro", ""),
				 "ch": ("Chamorro", ""),
				 "chb": ("Chibcha", ""),
				 "che": ("Chechen", ""),
				 "ce": ("Chechen", ""),
				 "chg": ("Chagatai", ""),
				 "chk": ("Chuukese", ""),
				 "chm": ("Mari", ""),
				 "chn": ("Chinook jargon", ""),
				 "cho": ("Choctaw", ""),
				 "chp": ("Chipewyan", ""),
				 "chr": ("Cherokee", ""),
				 "chu": ("Church Slavic", ""),
				 "cu": ("Church Slavic", ""),
				 "chv": ("Chuvash", ""),
				 "cv": ("Chuvash", ""),
				 "chy": ("Cheyenne", ""),
				 "cmc": ("Chamic languages", ""),
				 "cop": ("Coptic", ""),
				 "cor": ("Cornish", ""),
				 "kw": ("Cornish", ""),
				 "cos": ("Corsican", "Romance"),
				 "co": ("Corsican", "Romance"),
				 "cpe": ("Creoles and pidgins, English based (Other)", ""),
				 "cpf": ("Creoles and pidgins, French-based (Other)", ""),
				 "cpp": ("Creoles and pidgins, Portuguese-based (Other)", ""),
				 "cre": ("Cree", ""),
				 "crp": ("Creoles and pidgins (Other)", ""),
				 "cus": ("Cushitic (Other)", ""),
				 "cym": ("Welsh", "Celtic"),
				 "wel": ("Welsh", "Celtic"),
				 "cy": ("Welsh", "Celtic"),
				 "dak": ("Dakota", ""),
				 "dan": ("Danish", "Germanic"),
				 "da": ("Danish", "Germanic"),
				 "day": ("Dayak", ""),
				 "del": ("Delaware", ""),
				 "den": ("Slave (Athapascan)", ""),
				 "deu": ("German", "Germanic"),
				 "ger": ("German", "Germanic"),
				 "de": ("German", "Germanic"),
				 "dgr": ("Dogrib", ""),
				 "din": ("Dinka", ""),
				 "div": ("Divehi", ""),
				 "doi": ("Dogri", ""),
				 "dra": ("Dravidian (Other)", ""),
				 "dua": ("Duala", ""),
				 "dum": ("Dutch, Middle (ca. 1050-1350)", ""),
				 "dyu": ("Dyula", ""),
				 "dzo": ("Dzongkha", "Asian"),
				 "dz": ("Dzongkha", "Asian"),
				 "efi": ("Efik", ""),
				 "egy": ("Egyptian (Ancient)", ""),
				 "eka": ("Ekajuk", ""),
				 "ell": ("Greek, Modern (1453-)", "Latin/greek"),
				 "gre": ("Greek, Modern (1453-)", "Latin/greek"),
				 "el": ("Greek, Modern (1453-)", "Latin/greek"),
				 "elx": ("Elamite", ""),
				 "eng": ("English", "Germanic"),
				 "en": ("English", "Germanic"),
				 "enm": ("English, Middle (1100-1500)", ""),
				 "epo": ("Esperanto", "International aux."),
				 "eo": ("Esperanto", "International aux."),
				 "est": ("Estonian", "Finno-ugric"),
				 "et": ("Estonian", "Finno-ugric"),
				 "eus": ("Basque", "Basque"),
				 "baq": ("Basque", "Basque"),
				 "eu": ("Basque", "Basque"),
				 "ewe": ("Ewe", ""),
				 "ewo": ("Ewondo", ""),
				 "fan": ("Fang", ""),
				 "fao": ("Faroese", "Germanic"),
				 "fo": ("Faroese", "Germanic"),
				 "fas": ("Persian", ""),
				 "per": ("Persian", ""),
				 "fa": ("Persian", ""),
				 "fat": ("Fanti", ""),
				 "fij": ("Fijian", "Oceanic/indonesian"),
				 "fj": ("Fijian", "Oceanic/indonesian"),
				 "fin": ("Finnish", "Finno-ugric"),
				 "fi": ("Finnish", "Finno-ugric"),
				 "fiu": ("Finno-Ugrian (Other)", ""),
				 "fon": ("Fon", ""),
				 "fra": ("French", "Romance"),
				 "fre": ("French", "Romance"),
				 "fr": ("French", "Romance"),
				 "frm": ("French, Middle (ca. 1400-1600)", ""),
				 "fro": ("French, Old (842-ca. 1400)", ""),
				 "fry": ("Frisian", "Germanic"),
				 "fy": ("Frisian", "Germanic"),
				 "ful": ("Fulah", ""),
				 "fur": ("Friulian", ""),
				 "gaa": ("Ga", ""),
				 "gay": ("Gayo", ""),
				 "gba": ("Gbaya", ""),
				 "gem": ("Germanic (Other)", ""),
				 "gez": ("Geez", ""),
				 "gil": ("Gilbertese", ""),
				 "gla": ("Gaelic (Scots)", "Celtic"),
				 "gd": ("Gaelic (Scots)", "Celtic"),
				 "gle": ("Irish", "Celtic"),
				 "ga": ("Irish", "Celtic"),
				 "glg": ("Gallegan", "Romance"),
				 "gl": ("Gallegan", "Romance"),
				 "glv": ("Manx", ""),
				 "gv": ("Manx", ""),
				 "gmh": ("German, Middle High (ca. 1050-1500)", ""),
				 "goh": ("German, Old High (ca. 750-1050)", ""),
				 "gon": ("Gondi", ""),
				 "gor": ("Gorontalo", ""),
				 "got": ("Gothic", ""),
				 "grb": ("Grebo", ""),
				 "grc": ("Greek, Ancient (to 1453)", ""),
				 "grn": ("Guarani", "Amerindian"),
				 "gn": ("Guarani", "Amerindian"),
				 "guj": ("Gujarati", "Indian"),
				 "gu": ("Gujarati", "Indian"),
				 "gwi": ("Gwich´in", ""),
				 "hai": ("Haida", ""),
				 "hau": ("Hausa", "Negro-african"),
				 "ha": ("Hausa", "Negro-african"),
				 "haw": ("Hawaiian", ""),
				 "heb": ("Hebrew", ""),
				 "he": ("Hebrew", ""),
				 "her": ("Herero", ""),
				 "hz": ("Herero", ""),
				 "hil": ("Hiligaynon", ""),
				 "him": ("Himachali", ""),
				 "hin": ("Hindi", "Indian"),
				 "hi": ("Hindi", "Indian"),
				 "hit": ("Hittite", ""),
				 "hmn": ("Hmong", ""),
				 "hmo": ("Hiri Motu", ""),
				 "ho": ("Hiri Motu", ""),
				 "hrv": ("Croatian", "Slavic"),
				 "scr": ("Croatian", "Slavic"),
				 "hr": ("Croatian", "Slavic"),
				 "hun": ("Hungarian", "Finno-ugric"),
				 "hu": ("Hungarian", "Finno-ugric"),
				 "hup": ("Hupa", ""),
				 "hye": ("Armenian", "Indo-european (other)"),
				 "arm": ("Armenian", "Indo-european (other)"),
				 "hy": ("Armenian", "Indo-european (other)"),
				 "iba": ("Iban", ""),
				 "ibo": ("Igbo", ""),
				 "ijo": ("Ijo", ""),
				 "iku": ("Inuktitut", ""),
				 "iu": ("Inuktitut", ""),
				 "ile": ("Interlingue", "International aux."),
				 "ie": ("Interlingue", "International aux."),
				 "ilo": ("Iloko", ""),
				 "ina": ("Interlingua (International Auxiliary Language Association)", "International aux."),
				 "ia": ("Interlingua (International Auxiliary Language Association)", "International aux."),
				 "inc": ("Indic (Other)", ""),
				 "ind": ("Indonesian", ""),
				 "id": ("Indonesian", ""),
				 "ine": ("Indo-European (Other)", ""),
				 "ipk": ("Inupiaq", "Eskimo"),
				 "ik": ("Inupiaq", "Eskimo"),
				 "ira": ("Iranian (Other)", ""),
				 "iro": ("Iroquoian languages", ""),
				 "isl": ("Icelandic", "Germanic"),
				 "ice": ("Icelandic", "Germanic"),
				 "is": ("Icelandic", "Germanic"),
				 "ita": ("Italian", "Romance"),
				 "it": ("Italian", "Romance"),
				 "jaw": ("Javanese", ""),
				 "jav": ("Javanese", ""),
				 "jw": ("Javanese", ""),
				 "jpn": ("Japanese", "Asian"),
				 "ja": ("Japanese", "Asian"),
				 "jpr": ("Judeo-Persian", ""),
				 "kaa": ("Kara-Kalpak", ""),
				 "kab": ("Kabyle", ""),
				 "kac": ("Kachin", ""),
				 "kal": ("Kalaallisut", "Eskimo"),
				 "kl": ("Kalaallisut", "Eskimo"),
				 "kam": ("Kamba", ""),
				 "kan": ("Kannada", "Dravidian"),
				 "kn": ("Kannada", "Dravidian"),
				 "kar": ("Karen", ""),
				 "kas": ("Kashmiri", "Indian"),
				 "ks": ("Kashmiri", "Indian"),
				 "kat": ("Georgian", "Ibero-caucasian"),
				 "geo": ("Georgian", "Ibero-caucasian"),
				 "ka": ("Georgian", "Ibero-caucasian"),
				 "kau": ("Kanuri", ""),
				 "kaw": ("Kawi", ""),
				 "kaz": ("Kazakh", "Turkic/altaic"),
				 "kk": ("Kazakh", "Turkic/altaic"),
				 "kha": ("Khasi", ""),
				 "khi": ("Khoisan (Other)", ""),
				 "khm": ("Khmer", "Asian"),
				 "km": ("Khmer", "Asian"),
				 "kho": ("Khotanese", ""),
				 "kik": ("Kikuyu", ""),
				 "ki": ("Kikuyu", ""),
				 "kin": ("Kinyarwanda", "Negro-african"),
				 "rw": ("Kinyarwanda", "Negro-african"),
				 "kir": ("Kirghiz", "Turkic/altaic"),
				 "ky": ("Kirghiz", "Turkic/altaic"),
				 "kmb": ("Kimbundu", ""),
				 "kok": ("Konkani", ""),
				 "kom": ("Komi", ""),
				 "kv": ("Komi", ""),
				 "kon": ("Kongo", ""),
				 "kor": ("Korean", "Asian"),
				 "ko": ("Korean", "Asian"),
				 "kos": ("Kosraean", ""),
				 "kpe": ("Kpelle", ""),
				 "kro": ("Kru", ""),
				 "kru": ("Kurukh", ""),
				 "kum": ("Kumyk", ""),
				 "kur": ("Kurdish", "Iranian"),
				 "ku": ("Kurdish", "Iranian"),
				 "kut": ("Kutenai", ""),
				 "lad": ("Ladino", ""),
				 "lah": ("Lahnda", ""),
				 "lam": ("Lamba", ""),
				 "lao": ("Lao", "Asian"),
				 "lo": ("Lao", "Asian"),
				 "lat": ("Latin", "Latin/greek"),
				 "la": ("Latin", "Latin/greek"),
				 "lav": ("Latvian", "Baltic"),
				 "lv": ("Latvian", "Baltic"),
				 "lez": ("Lezghian", ""),
				 "lin": ("Lingala", "Negro-african"),
				 "ln": ("Lingala", "Negro-african"),
				 "lit": ("Lithuanian", "Baltic"),
				 "lt": ("Lithuanian", "Baltic"),
				 "lol": ("Mongo", ""),
				 "loz": ("Lozi", ""),
				 "ltz": ("Letzeburgesch", ""),
				 "lb": ("Letzeburgesch", ""),
				 "lua": ("Luba-Lulua", ""),
				 "lub": ("Luba-Katanga", ""),
				 "lug": ("Ganda", ""),
				 "lui": ("Luiseno", ""),
				 "lun": ("Lunda", ""),
				 "luo": ("Luo (Kenya and Tanzania)", ""),
				 "lus": ("lushai", ""),
				 "mad": ("Madurese", ""),
				 "mag": ("Magahi", ""),
				 "mah": ("Marshall", ""),
				 "mh": ("Marshall", ""),
				 "mai": ("Maithili", ""),
				 "mak": ("Makasar", ""),
				 "mal": ("Malayalam", "Dravidian"),
				 "ml": ("Malayalam", "Dravidian"),
				 "man": ("Mandingo", ""),
				 "map": ("Austronesian (Other)", ""),
				 "mar": ("Marathi", "Indian"),
				 "mr": ("Marathi", "Indian"),
				 "mas": ("Masai", ""),
				 "mdr": ("Mandar", ""),
				 "men": ("Mende", ""),
				 "mga": ("Irish, Middle (900-1200)", ""),
				 "mic": ("Micmac", ""),
				 "min": ("Minangkabau", ""),
				 "mis": ("Miscellaneous languages", ""),
				 "mkd": ("Macedonian", "Slavic"),
				 "mac": ("Macedonian", "Slavic"),
				 "mk": ("Macedonian", "Slavic"),
				 "mkh": ("Mon-Khmer (Other)", ""),
				 "mlg": ("Malagasy", "Oceanic/indonesian"),
				 "mg": ("Malagasy", "Oceanic/indonesian"),
				 "mlt": ("Maltese", "Semitic"),
				 "mt": ("Maltese", "Semitic"),
				 "mnc": ("Manchu", ""),
				 "mni": ("Manipuri", ""),
				 "mno": ("Manobo languages", ""),
				 "moh": ("Mohawk", ""),
				 "mol": ("Moldavian", "Romance"),
				 "mo": ("Moldavian", "Romance"),
				 "mon": ("Mongolian", ""),
				 "mn": ("Mongolian", ""),
				 "mos": ("Mossi", ""),
				 "mri": ("Maori", "Oceanic/indonesian"),
				 "mao": ("Maori", "Oceanic/indonesian"),
				 "mi": ("Maori", "Oceanic/indonesian"),
				 "msa": ("Malay", "Oceanic/indonesian"),
				 "may": ("Malay", "Oceanic/indonesian"),
				 "ms": ("Malay", "Oceanic/indonesian"),
				 "mul": ("Multiple languages", ""),
				 "mun": ("Munda languages", ""),
				 "mus": ("Creek", ""),
				 "mwr": ("Marwari", ""),
				 "mya": ("Burmese", "Asian"),
				 "bur": ("Burmese", "Asian"),
				 "my": ("Burmese", "Asian"),
				 "myn": ("Mayan languages", ""),
				 "nah": ("Nahuatl", ""),
				 "nai": ("North American Indian", ""),
				 "nau": ("Nauru", ""),
				 "na": ("Nauru", ""),
				 "nav": ("Navajo", ""),
				 "nv": ("Navajo", ""),
				 "nbl": ("Ndebele, South", ""),
				 "nr": ("Ndebele, South", ""),
				 "nde": ("Ndebele, North", ""),
				 "nd": ("Ndebele, North", ""),
				 "ndo": ("Ndonga", ""),
				 "ng": ("Ndonga", ""),
				 "nds": ("Low German; Low Saxon; German, Low; Saxon, Low", ""),
				 "nep": ("Nepali", "Indian"),
				 "ne": ("Nepali", "Indian"),
				 "new": ("Newari", ""),
				 "nia": ("Nias", ""),
				 "nic": ("Niger-Kordofanian (Other)", ""),
				 "niu": ("Niuean", ""),
				 "nld": ("Dutch", "Germanic"),
				 "dut": ("Dutch", "Germanic"),
				 "nl": ("Dutch", "Germanic"),
				 "nno": ("Norwegian Nynorsk", ""),
				 "nn": ("Norwegian Nynorsk", ""),
				 "nob": ("Norwegian Bokmĺl", ""),
				 "nb": ("Norwegian Bokmĺl", ""),
				 "non": ("Norse, Old", ""),
				 "nor": ("Norwegian", "Germanic"),
				 "no": ("Norwegian", "Germanic"),
				 "nso": ("Sotho, Northern", ""),
				 "nub": ("Nubian languages", ""),
				 "nya": ("Chichewa; Nyanja", ""),
				 "ny": ("Chichewa; Nyanja", ""),
				 "nym": ("Nyamwezi", ""),
				 "nyn": ("Nyankole", ""),
				 "nyo": ("Nyoro", ""),
				 "nzi": ("Nzima", ""),
				 "oci": ("Occitan (post 1500); Provençal", "Romance"),
				 "oc": ("Occitan (post 1500); Provençal", "Romance"),
				 "oji": ("Ojibwa", ""),
				 "ori": ("Oriya", "Indian"),
				 "or": ("Oriya", "Indian"),
				 "orm": ("Oromo", "Hamitic"),
				 "om": ("Oromo", "Hamitic"),
				 "osa": ("Osage", ""),
				 "oss": ("Ossetian; Ossetic", ""),
				 "os": ("Ossetian; Ossetic", ""),
				 "ota": ("Turkish, Ottoman (1500-1928)", ""),
				 "oto": ("Otomian languages", ""),
				 "paa": ("Papuan (Other)", ""),
				 "pag": ("Pangasinan", ""),
				 "pal": ("Pahlavi", ""),
				 "pam": ("Pampanga", ""),
				 "pan": ("Panjabi", "Indian"),
				 "pa": ("Panjabi", "Indian"),
				 "pap": ("Papiamento", ""),
				 "pau": ("Palauan", ""),
				 "peo": ("Persian, Old (ca. 600-400 b.c.)", ""),
				 "phi": ("Philippine (Other)", ""),
				 "pli": ("Pali", ""),
				 "pi": ("Pali", ""),
				 "pol": ("Polish", "Slavic"),
				 "pl": ("Polish", "Slavic"),
				 "pon": ("Pohnpeian", ""),
				 "por": ("Portuguese", "Romance"),
				 "pt": ("Portuguese", "Romance"),
				 "pra": ("Prakrit languages", ""),
				 "pro": ("Provençal, Old (to 1500)", ""),
				 "pus": ("Pushto", "Iranian"),
				 "ps": ("Pushto", "Iranian"),
				 "que": ("Quechua", "Amerindian"),
				 "qu": ("Quechua", "Amerindian"),
				 "raj": ("Rajasthani", ""),
				 "rap": ("Rapanui", ""),
				 "rar": ("Rarotongan", ""),
				 "roa": ("Romance (Other)", ""),
				 "rom": ("Romany", ""),
				 "ron": ("Romanian", "Romance"),
				 "rum": ("Romanian", "Romance"),
				 "ro": ("Romanian", "Romance"),
				 "run": ("Rundi", "Negro-african"),
				 "rn": ("Rundi", "Negro-african"),
				 "rus": ("Russian", "Slavic"),
				 "ru": ("Russian", "Slavic"),
				 "sad": ("Sandawe", ""),
				 "sag": ("Sango", "Negro-african"),
				 "sg": ("Sango", "Negro-african"),
				 "sah": ("Yakut", ""),
				 "sai": ("South American Indian (Other)", ""),
				 "sal": ("Salishan languages", ""),
				 "sam": ("Samaritan Aramaic", ""),
				 "san": ("Sanskrit", "Indian"),
				 "sa": ("Sanskrit", "Indian"),
				 "sas": ("Sasak", ""),
				 "sat": ("Santali", ""),
				 "sco": ("Scots", ""),
				 "sel": ("Selkup", ""),
				 "sem": ("Semitic (Other)", ""),
				 "sga": ("Irish, Old (to 900)", ""),
				 "sgn": ("Sign Languages", ""),
				 "shn": ("Shan", ""),
				 "sid": ("Sidamo", ""),
				 "sin": ("Sinhalese", "Indian"),
				 "si": ("Sinhalese", "Indian"),
				 "sio": ("Siouan languages", ""),
				 "sit": ("Sino-Tibetan (Other)", ""),
				 "sla": ("Slavic (Other)", ""),
				 "slk": ("Slovak", "Slavic"),
				 "slo": ("Slovak", "Slavic"),
				 "sk": ("Slovak", "Slavic"),
				 "slv": ("Slovenian", "Slavic"),
				 "sl": ("Slovenian", "Slavic"),
				 "sme": ("Northern Sami", ""),
				 "se": ("Northern Sami", ""),
				 "smi": ("Sami languages (Other)", ""),
				 "smo": ("Samoan", "Oceanic/indonesian"),
				 "sm": ("Samoan", "Oceanic/indonesian"),
				 "sna": ("Shona", "Negro-african"),
				 "sn": ("Shona", "Negro-african"),
				 "snd": ("Sindhi", "Indian"),
				 "sd": ("Sindhi", "Indian"),
				 "snk": ("Soninke", ""),
				 "sog": ("Sogdian", ""),
				 "som": ("Somali", "Hamitic"),
				 "so": ("Somali", "Hamitic"),
				 "son": ("Songhai", ""),
				 "sot": ("Sotho, Southern", "Negro-african"),
				 "st": ("Sotho, Southern", "Negro-african"),
				 "esl": ("Spanish", "Romance"),
				 "spa": ("Spanish", "Romance"),
				 "es": ("Spanish", "Romance"),
				 "sqi": ("Albanian", "Indo-european (other)"),
				 "alb": ("Albanian", "Indo-european (other)"),
				 "sq": ("Albanian", "Indo-european (other)"),
				 "srd": ("Sardinian", ""),
				 "sc": ("Sardinian", ""),
				 "srp": ("Serbian", "Slavic"),
				 "scc": ("Serbian", "Slavic"),
				 "sr": ("Serbian", "Slavic"),
				 "srr": ("Serer", ""),
				 "ssa": ("Nilo-Saharan (Other)", ""),
				 "ssw": ("Swati", "Negro-african"),
				 "ss": ("Swati", "Negro-african"),
				 "suk": ("Sukuma", ""),
				 "sun": ("Sundanese", "Oceanic/indonesian"),
				 "su": ("Sundanese", "Oceanic/indonesian"),
				 "sus": ("Susu", ""),
				 "sux": ("Sumerian", ""),
				 "swa": ("Swahili", "Negro-african"),
				 "sw": ("Swahili", "Negro-african"),
				 "swe": ("Swedish", "Germanic"),
				 "sv": ("Swedish", "Germanic"),
				 "syr": ("Syriac", ""),
				 "tah": ("Tahitian", ""),
				 "ty": ("Tahitian", ""),
				 "tai": ("Tai (Other)", ""),
				 "tam": ("Tamil", "Dravidian"),
				 "ta": ("Tamil", "Dravidian"),
				 "tat": ("Tatar", "Turkic/altaic"),
				 "tt": ("Tatar", "Turkic/altaic"),
				 "tel": ("Telugu", "Dravidian"),
				 "te": ("Telugu", "Dravidian"),
				 "tem": ("Timne", ""),
				 "ter": ("Tereno", ""),
				 "tet": ("Tetum", ""),
				 "tgk": ("Tajik", "Iranian"),
				 "tg": ("Tajik", "Iranian"),
				 "tgl": ("Tagalog", "Oceanic/indonesian"),
				 "tl": ("Tagalog", "Oceanic/indonesian"),
				 "tha": ("Thai", "Asian"),
				 "th": ("Thai", "Asian"),
				 "tig": ("Tigre", ""),
				 "tir": ("Tigrinya", "Semitic"),
				 "ti": ("Tigrinya", "Semitic"),
				 "tiv": ("Tiv", ""),
				 "tkl": ("Tokelau", ""),
				 "tli": ("Tlingit", ""),
				 "tmh": ("Tamashek", ""),
				 "tog": ("Tonga (Nyasa)", ""),
				 "ton": ("Tonga (Tonga Islands)", "Oceanic/indonesian"),
				 "to": ("Tonga (Tonga Islands)", "Oceanic/indonesian"),
				 "tpi": ("Tok Pisin", ""),
				 "tsi": ("Tsimshian", ""),
				 "tsn": ("Tswana", "Negro-african"),
				 "tn": ("Tswana", "Negro-african"),
				 "tso": ("Tsonga", "Negro-african"),
				 "ts": ("Tsonga", "Negro-african"),
				 "tuk": ("Turkmen", "Turkic/altaic"),
				 "tk": ("Turkmen", "Turkic/altaic"),
				 "tum": ("Tumbuka", ""),
				 "tur": ("Turkish", "Turkic/altaic"),
				 "tr": ("Turkish", "Turkic/altaic"),
				 "tut": ("Altaic (Other)", ""),
				 "tvl": ("Tuvalu", ""),
				 "twi": ("Twi", "Negro-african"),
				 "tw": ("Twi", "Negro-african"),
				 "tyv": ("Tuvinian", ""),
				 "uga": ("Ugaritic", ""),
				 "uig": ("Uighur", ""),
				 "ug": ("Uighur", ""),
				 "ukr": ("Ukrainian", "Slavic"),
				 "uk": ("Ukrainian", "Slavic"),
				 "umb": ("Umbundu", ""),
				 "und": ("Undetermined", ""),
				 "urd": ("Urdu", "Indian"),
				 "ur": ("Urdu", "Indian"),
				 "uzb": ("Uzbek", "Turkic/altaic"),
				 "uz": ("Uzbek", "Turkic/altaic"),
				 "vai": ("Vai", ""),
				 "ven": ("Venda", ""),
				 "vie": ("Vietnamese", "Asian"),
				 "vi": ("Vietnamese", "Asian"),
				 "vol": ("Volapük", "International aux."),
				 "vo": ("Volapük", "International aux."),
				 "vot": ("Votic", ""),
				 "wak": ("Wakashan languages", ""),
				 "wal": ("Walamo", ""),
				 "war": ("Waray", ""),
				 "was": ("Washo", ""),
				 "wen": ("Sorbian languages", ""),
				 "wol": ("Wolof", "Negro-african"),
				 "wo": ("Wolof", "Negro-african"),
				 "xho": ("Xhosa", "Negro-african"),
				 "xh": ("Xhosa", "Negro-african"),
				 "yao": ("Yao", ""),
				 "yap": ("Yapese", ""),
				 "yid": ("Yiddish", ""),
				 "yi": ("Yiddish", ""),
				 "yor": ("Yoruba", "Negro-african"),
				 "yo": ("Yoruba", "Negro-african"),
				 "ypk": ("Yupik languages", ""),
				 "zap": ("Zapotec", ""),
				 "zen": ("Zenaga", ""),
				 "zha": ("Zhuang", ""),
				 "za": ("Zhuang", ""),
				 "zho": ("Chinese", "Asian"),
				 "chi": ("Chinese", "Asian"),
				 "zh": ("Chinese", "Asian"),
				 "znd": ("Zande", ""),
				 "zul": ("Zulu", "Negro-african"),
				 "zu": ("Zulu", "Negro-african"),
				 "zun": ("Zuni", "")}

