# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fu', [dirname(__file__)])
        except ImportError:
            import _fu
            return _fu
        if fp is not None:
            try:
                _mod = imp.load_module('_fu', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _fu = swig_import_helper()
    del swig_import_helper
else:
    import _fu
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class FU(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FU, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FU, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _fu.new_FU()
        try: self.this.append(this)
        except: self.this = this
    def getStatus(self): return _fu.FU_getStatus(self)
    def getInterval(self): return _fu.FU_getInterval(self)
    def checkError(self): return _fu.FU_checkError(self)
    def getErrorMessage(self, *args): return _fu.FU_getErrorMessage(self, *args)
    def startUpgrade(self, *args): return _fu.FU_startUpgrade(self, *args)
    def getDataPath(self): return _fu.FU_getDataPath(self)
    def getDevicePath(self): return _fu.FU_getDevicePath(self)
    __swig_destroy__ = _fu.delete_FU
    __del__ = lambda self : None;
FU_swigregister = _fu.FU_swigregister
FU_swigregister(FU)



