# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.39
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fpga', [dirname(__file__)])
        except ImportError:
            import _fpga
            return _fpga
        if fp is not None:
            try:
                _mod = imp.load_module('_fpga', fp, pathname, description)
            finally:
                fp.close()
                return _mod
    _fpga = swig_import_helper()
    del swig_import_helper
else:
    import _fpga
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


DP_NO_ACTION_FOUND = _fpga.DP_NO_ACTION_FOUND
DP_DEVICE_INFO_ACTION_CODE = _fpga.DP_DEVICE_INFO_ACTION_CODE
DP_READ_IDCODE_ACTION_CODE = _fpga.DP_READ_IDCODE_ACTION_CODE
DP_ERASE_ACTION_CODE = _fpga.DP_ERASE_ACTION_CODE
DP_PROGRAM_ACTION_CODE = _fpga.DP_PROGRAM_ACTION_CODE
DP_VERIFY_ACTION_CODE = _fpga.DP_VERIFY_ACTION_CODE
NO_SRC_FILE_PATH = _fpga.NO_SRC_FILE_PATH
NO_TAR_DEVICE_PATH = _fpga.NO_TAR_DEVICE_PATH
FAIL_OPEN_SRC_FILE = _fpga.FAIL_OPEN_SRC_FILE
ZERO_SRC_FILE_SIZE = _fpga.ZERO_SRC_FILE_SIZE
FAIL_OPEN_DEVICE = _fpga.FAIL_OPEN_DEVICE
class Fpga(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Fpga, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Fpga, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _fpga.new_Fpga()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _fpga.delete_Fpga
    __del__ = lambda self : None;
    def get_interval(self): return _fpga.Fpga_get_interval(self)
    def get_error_msg(self, *args): return _fpga.Fpga_get_error_msg(self, *args)
    def fpga_upgrade(self, *args): return _fpga.Fpga_fpga_upgrade(self, *args)
    def get_status(self): return _fpga.Fpga_get_status(self)
Fpga_swigregister = _fpga.Fpga_swigregister
Fpga_swigregister(Fpga)



