#read the comment to this file in lib/service/iservice.h !!
from os import remove, rename
import sys

filename = sys.argv[1]  # NOSONAR
rename(filename, filename + ".org")

source = open(filename + ".org")  # NOSONAR
dest = open(filename, "w")  # NOSONAR

for line, str in enumerate(source):
	oldstr = str[:]
	str = str.replace('_ENUMS)', ')')

	pos = str.find('_ENUMS')
	if pos != -1:
		spacepos = pos
		while spacepos > 0 and str[spacepos] != ' ':
			spacepos -= 1
		tmpstr = str[spacepos:pos]
		if '_enigma.' not in tmpstr:
			str = str[:pos] + str[pos + 6:]

	if oldstr != str:
		print("!!! Patch enigma.py line %d\n%s\n%s" % (line, oldstr[:len(oldstr) - 1], str))

	dest.write(str)

# ---------------------------------------------------------------------------
# HbbTV backend compatibility glue.
#
# OpenATV SWIG exposes PSignal members as wrapper objects whose get() method
# returns a Python callback list.  Dream HbbTV code expects signal.connect(...).
# Therefore we keep the original generated signal properties and add connect()
# to the PSignal wrapper classes.  connect() appends the callback to the
# underlying list.
#
# Also expose getApplicationIdsAndName() as a real Python method calling the
# generated getApplicationIdsAndNamePy() helper.
# ---------------------------------------------------------------------------
dest.write(r'''

# ---------------------------------------------------------------------------
# HbbTV backend compatibility glue.
# This block is generated by lib/python/enigma_py_patcher.py.
# ---------------------------------------------------------------------------

class _HbbTVSignalConnection:
	def __init__(self, callbacks, slot):
		if not callable(slot):
			raise TypeError("Signal callback must be callable")
		self._callbacks = callbacks

		def callback(*args):
			return slot(*args)

		self._callback = callback
		callbacks.append(callback)

	def disconnect(self):
		if self._callbacks is not None:
			try:
				self._callbacks.remove(self._callback)
			except ValueError:
				pass
			self._callbacks = None
			self._callback = None


def _hbbtvPatchSignalWrapper(className):
	wrapperClass = globals().get(className)
	if wrapperClass is None:
		return

	if hasattr(wrapperClass, "connect"):
		return

	if not hasattr(wrapperClass, "get"):
		return

	def _connect(self, slot):
		callbacks = self.get()
		if hasattr(callbacks, "connect"):
			return callbacks.connect(slot)
		if hasattr(callbacks, "append"):
			return _HbbTVSignalConnection(callbacks, slot)
		raise AttributeError("Signal callback container has no connect or append")

	wrapperClass.connect = _connect


def _hbbtvGetApplicationIdsAndName(self):
	return self.getApplicationIdsAndNamePy()


def _hbbtvPatchEHbbtv():
	try:
		for className in (
			"PSignal0V",
			"PSignal1VS",
			"PSignal1VI",
			"PSignal4VIIII",
		):
			_hbbtvPatchSignalWrapper(className)

		if hasattr(eHbbtv, "getApplicationIdsAndNamePy"):
			eHbbtv.getApplicationIdsAndName = _hbbtvGetApplicationIdsAndName

	except NameError:
		pass


_hbbtvPatchEHbbtv()

# ---------------------------------------------------------------------------
# End HbbTV backend compatibility glue.
# ---------------------------------------------------------------------------

''')

del source
del dest
remove(filename + ".org")  # NOSONAR
