#!/bin/sh

scriptName=`basename $0 .sh`

rm -rf "${sysconfdir}"/enigma2
cp -a "${datadir}"/enigma2/defaults "${sysconfdir}"/enigma2

rm -rf "${sysconfdir}"/network/interfaces

# /etc/network/interfaces as in distribution.
# Should be replaced by a copy from a defaults file ASAP.

cat > "${sysconfdir}"/network/interfaces << '__EOF'
# /etc/network/interfaces -- configuration file for ifup(8), ifdown(8)
 
# The loopback interface
auto lo
iface lo inet loopback

# Wireless interfaces
iface wlan0 inet dhcp
	wireless_mode managed
	wireless_essid any
	wpa-driver wext
	wpa-conf /etc/wpa_supplicant.conf

iface atml0 inet dhcp

# Wired or wireless interfaces
auto eth0
iface eth0 inet dhcp
iface eth1 inet dhcp

# Ethernet/RNDIS gadget (g_ether)
# ... or on host side, usbnet and random hwaddr
iface usb0 inet static
	address 192.168.7.2
	netmask 255.255.255.0
	network 192.168.7.0
	gateway 192.168.7.1

# Bluetooth networking
iface bnep0 inet dhcp

__EOF

rm -rf "${sysconfdir}"/wpa_supplicant.ath0.conf
rm -rf "${sysconfdir}"/wpa_supplicant.wlan0.conf
rm -rf "${sysconfdir}"/wpa_supplicant.conf
