# -*- coding: UTF-8 -*-
LANG_TEXT = {
"en_EN": {
	"fr_FR": "French",
	"fi_FI": "Finnish",
	"pt_PT": "Portuguese",
	"fy_x-FY": "Frisian",
	"it_IT": "Italian",
	"no_NO": "Norwegian",
	"nl_NL": "Dutch",
	"el_GR": "Greek",
	"hu_HU": "Hungarian",
	"lt_LT": "Lithuanian",
	"hr_HR": "Croatian",
	"en_EN": "English",
	"es_ES": "Spanish",
	"ca_AD": "Catalan",
	"ru_RU": "Russian",
	"is_IS": "Icelandic",
	"da_DK": "Danish",
	"cs_CZ": "Czech",
	"tr_TR": "Turkish",
	"de_DE": "German",
	"ar_AE": "Arabic",
	"uk_UA": "Ukrainian",
	"sv_SE": "Swedish",
	"pl_PL": "Polish",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Language selection",
},
"de_DE": {
	"fr_FR": "Französisch",
	"fi_FI": "Finnisch",
	"pt_PT": "portugiesisch",
	"fy_x-FY": "Frisian",
	"it_IT": "Italienisch",
	"no_NO": "Norwegisch",
	"nl_NL": "Holländisch",
	"el_GR": "Griechisch",
	"hu_HU": "Ungarisch",
	"lt_LT": "litauisch",
	"hr_HR": "Kroatisch",
	"en_EN": "Englisch",
	"es_ES": "Spanisch",
	"ca_AD": "Katalanisch",
	"ru_RU": "Russisch",
	"is_IS": "Isländisch",
	"da_DK": "Dänisch",
	"cs_CZ": "Tschechisch",
	"tr_TR": "Türkisch",
	"de_DE": "Deutsch",
	"ar_AE": "Arabisch",
	"uk_UA": "Ukrainian",
	"sv_SE": "Schwedisch",
	"pl_PL": "Polnisch",
	"T1": "Bitte benutzen Sie die Hoch/Runter-Tasten, um Ihre Sprache auszuwählen. Danach drücken Sie bitte OK.",
	"T2": "Sprachauswahl",
},
"ar_AE": {
	"fr_FR": "French",
	"fi_FI": "Finnish",
	"pt_PT": "Portuguese",
	"fy_x-FY": "Frisian",
	"it_IT": "Italian",
	"no_NO": "Norwegian",
	"nl_NL": "Dutch",
	"el_GR": "Greek",
	"hu_HU": "Hungarian",
	"lt_LT": "Lithuanian",
	"hr_HR": "Croatian",
	"en_EN": "إنجليزى",
	"es_ES": "Spanish",
	"ca_AD": "Catalan",
	"ru_RU": "Russian",
	"is_IS": "Icelandic",
	"da_DK": "Danish",
	"cs_CZ": "Czech",
	"tr_TR": "Turkish",
	"de_DE": "المانـى",
	"ar_AE": "Arabic",
	"uk_UA": "Ukrainian",
	"sv_SE": "Swedish",
	"pl_PL": "Polish",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "إختيار اللغه",
},
"ca_AD": {
	"fr_FR": "Francès",
	"fi_FI": "Finlandès",
	"pt_PT": "Portuguès",
	"fy_x-FY": "Frisian",
	"it_IT": "Italià",
	"no_NO": "Noruec",
	"nl_NL": "Holandès",
	"el_GR": "Grec",
	"hu_HU": "Hongarès",
	"lt_LT": "Lituà",
	"hr_HR": "Croat",
	"en_EN": "Anglès",
	"es_ES": "Espanyol",
	"ca_AD": "Català",
	"ru_RU": "Rus",
	"is_IS": "Islandès",
	"da_DK": "Danès",
	"cs_CZ": "Txec",
	"tr_TR": "Turc",
	"de_DE": "Alemany",
	"ar_AE": "Àrab",
	"uk_UA": "Ukrainian",
	"sv_SE": "Suec",
	"pl_PL": "Polish",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Selecció d'idioma",
},
"hr_HR": {
	"fr_FR": "Francuski",
	"fi_FI": "Finski",
	"pt_PT": "Portugalski",
	"fy_x-FY": "Frisian",
	"it_IT": "Talijanski",
	"no_NO": "Norveški",
	"nl_NL": "Nizozemski",
	"el_GR": "Grčki",
	"hu_HU": "Mađarski",
	"lt_LT": "Litvanski",
	"hr_HR": "Hrvatski",
	"en_EN": "Engleski",
	"es_ES": "Španjolski",
	"ca_AD": "Katalonski",
	"ru_RU": "Ruski",
	"is_IS": "Islandski",
	"da_DK": "Danski",
	"cs_CZ": "Češki",
	"tr_TR": "Turski",
	"de_DE": "Njemački",
	"ar_AE": "Arabski",
	"uk_UA": "Ukrainian",
	"sv_SE": "Švedski",
	"pl_PL": "Poljski",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Odaberite Jezik",
},
"cs_CZ": {
	"fr_FR": "Francouzsky",
	"fi_FI": "Finsky",
	"pt_PT": "Portugalsky",
	"fy_x-FY": "Frisian",
	"it_IT": "Italsky",
	"no_NO": "Norsky",
	"nl_NL": "Holandsky",
	"el_GR": "Řecky",
	"hu_HU": "Maďarsky",
	"lt_LT": "Litevsky",
	"hr_HR": "Chorvatsky",
	"en_EN": "Anglicky",
	"es_ES": "Španělsky",
	"ca_AD": "Katalánsky",
	"ru_RU": "Rusky",
	"is_IS": "Islandsky",
	"da_DK": "Dánsky",
	"cs_CZ": "Česky",
	"tr_TR": "Turecky",
	"de_DE": "Německy",
	"ar_AE": "Arabsky",
	"uk_UA": "Ukrainian",
	"sv_SE": "Švédsky",
	"pl_PL": "Polsky",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Výběr jazyka",
},
"da_DK": {
	"fr_FR": "Fransk",
	"fi_FI": "Finsk",
	"pt_PT": "Portugisisk",
	"fy_x-FY": "Frisian",
	"it_IT": "Italiensk",
	"no_NO": "Norsk",
	"nl_NL": "Hollandsk",
	"el_GR": "Græsk",
	"hu_HU": "Ungarsk",
	"lt_LT": "Litauisk",
	"hr_HR": "Kroatisk",
	"en_EN": "Engelsk",
	"es_ES": "Spansk",
	"ca_AD": "Catalansk",
	"ru_RU": "Russisk",
	"is_IS": "Islandsk",
	"da_DK": "Dansk",
	"cs_CZ": "Tjekkisk",
	"tr_TR": "Tyrkisk",
	"de_DE": "Tysk",
	"ar_AE": "Arabisk",
	"uk_UA": "Ukrainian",
	"sv_SE": "Svensk",
	"pl_PL": "Polsk",
	"T1": "Benyt venligst OP og NED tasten til at vælge sprog. Tryk bagefter på OK knappen.",
	"T2": "Valg af Sprog",
},
"nl_NL": {
	"fr_FR": "Frans",
	"fi_FI": "Fins",
	"pt_PT": "Portugees",
	"fy_x-FY": "Frisian",
	"it_IT": "Italiaans",
	"no_NO": "Noors",
	"nl_NL": "Nederlands",
	"el_GR": "Grieks",
	"hu_HU": "Hongaars",
	"lt_LT": "Litouws",
	"hr_HR": "Kroatisch",
	"en_EN": "Engels",
	"es_ES": "Spaans",
	"ca_AD": "Catalaans",
	"ru_RU": "Russisch",
	"is_IS": "Ijslands",
	"da_DK": "Deens",
	"cs_CZ": "Tsjechisch",
	"tr_TR": "Turks",
	"de_DE": "Duits",
	"ar_AE": "Arabisch",
	"uk_UA": "Ukrainian",
	"sv_SE": "Zweeds",
	"pl_PL": "Pools",
	"T1": "Gebruik de omhoog/omlaag toeten om de gewenste taal te selecteren. Druk daarna op OK.",
	"T2": "Taalkeuze",
},
"fi_FI": {
	"fr_FR": "Ranska",
	"fi_FI": "Suomi",
	"pt_PT": "Portugali",
	"fy_x-FY": "Frisian",
	"it_IT": "Italia",
	"no_NO": "Norja",
	"nl_NL": "Hollanti",
	"el_GR": "Kreikka",
	"hu_HU": "Unkari",
	"lt_LT": "Liettua",
	"hr_HR": "Kroatia",
	"en_EN": "Englanti",
	"es_ES": "Espanja",
	"ca_AD": "Katalaani",
	"ru_RU": "Venäjä",
	"is_IS": "Islanti",
	"da_DK": "Tanska",
	"cs_CZ": "Tšekki",
	"tr_TR": "Turkki",
	"de_DE": "Saksa",
	"ar_AE": "Arabia",
	"uk_UA": "Ukrainian",
	"sv_SE": "Ruotsi",
	"pl_PL": "Puola",
	"T1": "Valitse kieli ylös/alas näppäimillä ja paina OK-näppäintä.",
	"T2": "Kielivalinta",
},
"fr_FR": {
	"fr_FR": "Français",
	"fi_FI": "Finlandais",
	"pt_PT": "Portugais",
	"fy_x-FY": "Frisian",
	"it_IT": "Italien",
	"no_NO": "Norvégien",
	"nl_NL": "Hollandais",
	"el_GR": "Grèque",
	"hu_HU": "hongrois",
	"lt_LT": "Lithuanien",
	"hr_HR": "Croate",
	"en_EN": "Anglais",
	"es_ES": "Espagnol",
	"ca_AD": "Catalan",
	"ru_RU": "Russe",
	"is_IS": "Islandais",
	"da_DK": "Danois",
	"cs_CZ": "Tchèque",
	"tr_TR": "Turke",
	"de_DE": "Allemand",
	"ar_AE": "Arabe",
	"uk_UA": "Ukrainian",
	"sv_SE": "Suédois",
	"pl_PL": "Polonais",
	"T1": "Veuillez utiliser les touches HAUT et BAS pour choisir votre langage. Ensuite presser le bouton OK.",
	"T2": "Sélection de la langue",
},
"el_GR": {
	"fr_FR": "Γαλλικά",
	"fi_FI": "Φιλλανδικά",
	"pt_PT": "Πορτογαλλικά",
	"fy_x-FY": "Frisian",
	"it_IT": "Ιταλικά",
	"no_NO": "Νορβηφικά",
	"nl_NL": "Ολλανδικά",
	"el_GR": "Ελληνικά",
	"hu_HU": "Ουγγαρεζικά",
	"lt_LT": "Λιθουανικά",
	"hr_HR": "Κροάτικα",
	"en_EN": "Αγγλικά",
	"es_ES": "Ισπανικά",
	"ca_AD": "Catalan",
	"ru_RU": "Ρωσικά",
	"is_IS": "Ισλανδικά",
	"da_DK": "Δανικά",
	"cs_CZ": "Τσέχικα",
	"tr_TR": "Τούρκικα",
	"de_DE": "Γερμανικά",
	"ar_AE": "Αραβικά",
	"uk_UA": "Ukrainian",
	"sv_SE": "Σουιδεζικά",
	"pl_PL": "Πολωνικά",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Επιλογή γλώσσας",
},
"hu_HU": {
	"fr_FR": "Francia",
	"fi_FI": "Finn",
	"pt_PT": "Portugál",
	"fy_x-FY": "Frisian",
	"it_IT": "Olasz",
	"no_NO": "Norvég",
	"nl_NL": "Holland",
	"el_GR": "Görög",
	"hu_HU": "Magyar",
	"lt_LT": "Litván",
	"hr_HR": "Horvát",
	"en_EN": "Angol",
	"es_ES": "Spanyol",
	"ca_AD": "Katalán",
	"ru_RU": "Orosz",
	"is_IS": "Izlandi",
	"da_DK": "Dán",
	"cs_CZ": "Cseh",
	"tr_TR": "Török",
	"de_DE": "Német",
	"ar_AE": "Arab",
	"uk_UA": "Ukrainian",
	"sv_SE": "Svéd",
	"pl_PL": "Lengyel",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Válasszon nyelvet",
},
"lt_LT": {
	"fr_FR": "Prancūzų",
	"fi_FI": "Suomių",
	"pt_PT": "Portugalų",
	"fy_x-FY": "Frisian",
	"it_IT": "Italų",
	"no_NO": "Norvegų",
	"nl_NL": "Olandų",
	"el_GR": "Graikų",
	"hu_HU": "Vengrų",
	"lt_LT": "Lietuvių",
	"hr_HR": "Kroatų",
	"en_EN": "Anglų",
	"es_ES": "Ispanų",
	"ca_AD": "Katalonų",
	"ru_RU": "Rusų",
	"is_IS": "Islandų",
	"da_DK": "Danų",
	"cs_CZ": "Čekų",
	"tr_TR": "Turkų",
	"de_DE": "Vokiečių",
	"ar_AE": "Arabų",
	"uk_UA": "Ukrainiečių",
	"sv_SE": "Švedų",
	"pl_PL": "Lenkų",
	"T1": "Prašome naudoti AUKŠTYN IR ŽEMYN mygtukus, kad išsirinktumėte savo kalbą. Po to spauskite OK mygtuką.",
	"T2": "Kalbos pasirinkimas",
},
"is_IS": {
	"fr_FR": "Franska",
	"fi_FI": "Finnska",
	"pt_PT": "Portúgalska",
	"fy_x-FY": "Frisian",
	"it_IT": "Ítalska",
	"no_NO": "Norska",
	"nl_NL": "Hollenska",
	"el_GR": "Gríska",
	"hu_HU": "Ungverska",
	"lt_LT": "Litháíska",
	"hr_HR": "Króatíska",
	"en_EN": "Enska",
	"es_ES": "Spænska",
	"ca_AD": "Catalan",
	"ru_RU": "Rússneska",
	"is_IS": "Íslenska",
	"da_DK": "Danska",
	"cs_CZ": "Tékkneska",
	"tr_TR": "Tyrkneska",
	"de_DE": "Þýska",
	"ar_AE": "Arabíska",
	"uk_UA": "Ukrainian",
	"sv_SE": "Sænskt",
	"pl_PL": "Pólska",
	"T1": "Vinsamlega notið UP og NIÐUR takka til að velja tungumál. Ýttu svo á OK til að nota.",
	"T2": "Val tungumáls",
},
"it_IT": {
	"fr_FR": "Francese",
	"fi_FI": "Finlandese",
	"pt_PT": "Portoghese",
	"fy_x-FY": "Frisian",
	"it_IT": "Italiano",
	"no_NO": "Norvegese",
	"nl_NL": "Olandese",
	"el_GR": "Greco",
	"hu_HU": "Ungherese",
	"lt_LT": "Lituano",
	"hr_HR": "Croato",
	"en_EN": "Inglese",
	"es_ES": "Spagnolo",
	"ca_AD": "Catalano",
	"ru_RU": "Russo",
	"is_IS": "Islandese",
	"da_DK": "Danese",
	"cs_CZ": "Ceco",
	"tr_TR": "Turco",
	"de_DE": "Tedesco",
	"ar_AE": "Arabo",
	"uk_UA": "Ucraino",
	"sv_SE": "Svedese",
	"pl_PL": "Polacco",
	"T1": "Selezionare la propria lingua utilizzando i tasti Sù/Giù. Premere OK per confermare.",
	"T2": "Selezione lingua",
},
"no_NO": {
	"fr_FR": "Fransk",
	"fi_FI": "Finsk",
	"pt_PT": "Portugisisk",
	"fy_x-FY": "Frisian",
	"it_IT": "Italiensk",
	"no_NO": "Norsk",
	"nl_NL": "Nederlandsk",
	"el_GR": "Gresk",
	"hu_HU": "Ungarsk",
	"lt_LT": "Litauisk",
	"hr_HR": "Kroatisk",
	"en_EN": "Engelsk",
	"es_ES": "Spansk",
	"ca_AD": "Katalansk",
	"ru_RU": "Russisk",
	"is_IS": "Islandsk",
	"da_DK": "Dansk",
	"cs_CZ": "Tjekkisk",
	"tr_TR": "Tyrkisk",
	"de_DE": "Tysk",
	"ar_AE": "Arabisk",
	"uk_UA": "Ukrainian",
	"sv_SE": "Svensk",
	"pl_PL": "Polsk",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Språkvalg",
},
"pl_PL": {
	"fr_FR": "Francuski",
	"fi_FI": "Fiński",
	"pt_PT": "Portugalski",
	"fy_x-FY": "Frisian",
	"it_IT": "Włoski",
	"no_NO": "Norweski",
	"nl_NL": "Holenderski",
	"el_GR": "Grecki",
	"hu_HU": "Węgierski",
	"lt_LT": "Litewski",
	"hr_HR": "Chorwacki",
	"en_EN": "Angielski",
	"es_ES": "Hiszpański",
	"ca_AD": "Hiszpański",
	"ru_RU": "Rosyjski",
	"is_IS": "Islandzki",
	"da_DK": "Duński",
	"cs_CZ": "Czeski",
	"tr_TR": "Turecki",
	"de_DE": "Niemiecki",
	"ar_AE": "Arabski",
	"uk_UA": "Ukrainian",
	"sv_SE": "Szwedzki",
	"pl_PL": "Polski",
	"T1": "W celu wyboru języka użyj klawiszy GÓRA i DÓŁ. Nastepnie nacisnij przycisk OK.",
	"T2": "Wybór języka",
},
"pt_PT": {
	"fr_FR": "Francês",
	"fi_FI": "Finlandês",
	"pt_PT": "Português",
	"fy_x-FY": "Frisian",
	"it_IT": "Italiano",
	"no_NO": "Norueguês",
	"nl_NL": "Holandês",
	"el_GR": "Grego",
	"hu_HU": "Hungaro",
	"lt_LT": "Lituano",
	"hr_HR": "Croata",
	"en_EN": "Inglês",
	"es_ES": "Catalão",
	"ca_AD": "Catalão",
	"ru_RU": "Russo",
	"is_IS": "Islandês",
	"da_DK": "Dinamarquês",
	"cs_CZ": "Checo",
	"tr_TR": "Turco",
	"de_DE": "Alemão",
	"ar_AE": "Arabe",
	"uk_UA": "Ukrainian",
	"sv_SE": "Sueco",
	"pl_PL": "Polaco",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Selecção do Idioma",
},
"ru_RU": {
	"fr_FR": "Французский",
	"fi_FI": "Окончание",
	"pt_PT": "Portuguese",
	"fy_x-FY": "Frisian",
	"it_IT": "Итальянский",
	"no_NO": "Норвежский",
	"nl_NL": "Нидерландский",
	"el_GR": "Greek",
	"hu_HU": "Hungarian",
	"lt_LT": "Lithuanian",
	"hr_HR": "Croatian",
	"en_EN": "Английский",
	"es_ES": "Испанский",
	"ca_AD": "Catalan",
	"ru_RU": "Русский",
	"is_IS": "Исландский",
	"da_DK": "Датский",
	"cs_CZ": "Czech",
	"tr_TR": "Турецкий",
	"de_DE": "Немецкий",
	"ar_AE": "Арабский",
	"uk_UA": "Ukrainian",
	"sv_SE": "Шведский",
	"pl_PL": "Polish",
	"T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	"T2": "Выбор языка",
},
"es_ES": {
	"fr_FR": "Francés",
	"fi_FI": "Finlandés",
	"pt_PT": "Portugués",
	"fy_x-FY": "Frisian",
	"it_IT": "Italiano",
	"no_NO": "Noruego",
	"nl_NL": "Alemán",
	"el_GR": "Griego",
	"hu_HU": "Húngaro",
	"lt_LT": "Lituano",
	"hr_HR": "Croata",
	"en_EN": "Inglés",
	"es_ES": "Español",
	"ca_AD": "Catalán",
	"ru_RU": "Ruso",
	"is_IS": "Islandés",
	"da_DK": "Danés",
	"cs_CZ": "Checo",
	"tr_TR": "Turco",
	"de_DE": "Alemán",
	"ar_AE": "Arábigo",
	"uk_UA": "Ukrainian",
	"sv_SE": "Sueco",
	"pl_PL": "Polaco",
	"T1": "Use las teclas ARRIBA y ABAJO para seleccionar su idioma. Después, pulse el botón OK.",
	"T2": "Selección de idioma",
},
"sv_SE": {
	"fr_FR": "Franska",
	"fi_FI": "Finska",
	"pt_PT": "Portugisiska",
	"fy_x-FY": "Frisian",
	"it_IT": "Italienska",
	"no_NO": "Norska",
	"nl_NL": "Holländska",
	"el_GR": "Grekiska",
	"hu_HU": "Ungerska",
	"lt_LT": "Litauiska",
	"hr_HR": "Kroatiska",
	"en_EN": "Engelska",
	"es_ES": "Spanska",
	"ca_AD": "Katalanska",
	"ru_RU": "Ryska",
	"is_IS": "Isländska",
	"da_DK": "Danska",
	"cs_CZ": "Tjeckiska",
	"tr_TR": "Turkiska",
	"de_DE": "Tyska",
	"ar_AE": "Arabiska",
	"uk_UA": "Ukrainian",
	"sv_SE": "Svenska",
	"pl_PL": "Polska",
	"T1": "Vänligen använd UPP och NER pil för att välja språk. Efter val tryck på OK knappen.",
	"T2": "Välj språk",
},
"tr_TR": {
	"fr_FR": "Fransızca",
	"fi_FI": "Fince",
	"pt_PT": "Portekizce",
	"fy_x-FY": "Frisian",
	"it_IT": "İtalyanca",
	"no_NO": "Norveççe",
	"nl_NL": "Flemenkçe",
	"el_GR": "Greek",
	"hu_HU": "Macarca",
	"lt_LT": "Litvanyaca",
	"hr_HR": "Hırvatça",
	"en_EN": "İngilizce",
	"es_ES": "İspanyolca",
	"ca_AD": "Katalanca",
	"ru_RU": "Rusça",
	"is_IS": "İzlandaca",
	"da_DK": "Danca",
	"cs_CZ": "Çekçe",
	"tr_TR": "Türkçe",
	"de_DE": "Almanca",
	"ar_AE": "Arapça",
	"uk_UA": "Ukraynaca",
	"sv_SE": "İsveççe",
	"pl_PL": "Polish",
	"T1": "Dil seçiminizi, yapmak için YUKARI ve AŞAĞI tuşlarını, onaylamak için OK tuşunu kullanın.",
	"T2": "Dil seçimi",
},
"uk_UA": {
	"fr_FR": "Французька",
	"fi_FI": "Фінська",
	"pt_PT": "Португальська",
	"fy_x-FY": "Frisian",
	"it_IT": "Італійська",
	"no_NO": "Норвежська",
	"nl_NL": "Данська",
	"el_GR": "Грецька",
	"hu_HU": "Угорська",
	"lt_LT": "Литовська",
	"hr_HR": "Хорватьска",
	"en_EN": "Англійська",
	"es_ES": "Іспанська",
	"ca_AD": "Каталонська",
	"ru_RU": "Російська",
	"is_IS": "Ісландська",
	"da_DK": "Данська",
	"cs_CZ": "Чешська",
	"tr_TR": "Турецька",
	"de_DE": "Німецька",
	"ar_AE": "Арабський",
	"uk_UA": "Ukrainian",
	"sv_SE": "Шведська",
	"pl_PL": "Польська",
	"T1": "Використовуйте кнопки ВВЕРХ і ВНИЗ, щоб вибрати Вашу мову. Після вибору натисніть OK.",
	"T2": "Вибір мови",
},
"fy_x-FY": {
	"fr_FR": "Frans",
	"fi_FI": "Finsk",
	"pt_PT": "Portugeesk",
	"fy_x-FY": "Frisian",
	"it_IT": "Italiaansk",
	"no_NO": "Noarsk",
	"nl_NL": "Nederlansk",
	"el_GR": "Gryks",
	"hu_HU": "Hongaarsk",
	"lt_LT": "Lithuaniansk",
	"hr_HR": "Kroatysk",
	"en_EN": "Engelsk",
	"es_ES": "Spaans",
	"ca_AD": "Catalânsk",
	"ru_RU": "Russysk",
	"is_IS": "Iislansk",
	"da_DK": "Deensk",
	"cs_CZ": "Tsjechysk",
	"tr_TR": "Turks",
	"de_DE": "Dúts",
	"ar_AE": "Arabysk",
	"uk_UA": "Ukrainian",
	"sv_SE": "Zweeds",
	"pl_PL": "Poolsk",
	"T1": "Brúk de op en del toets om jo taal te kiezen. Dernei druk op OK",
	"T2": "Taal Kieze",
},
}
