# -*- coding: UTF-8 -*-
# date: 30.08.2014  13:39:12
#

LANG_TEXT = {
"de_DE": {
	 "T1": "Für Sprachauswahl Hoch/Runter-Tasten nutzen. Danach OK drücken.",
	 "T2": "Sprachauswahl",
	 "T3": "Abbrechen",
	 "T4": "Speichern",
},
"ar_AE": {
	 "T1": "من فضلك أستخدم ذر السهم العلوى أو السفلى لإختيار اللغه. ثم أضغط موافق .",
	 "T2": "إختيار اللغـه",
	 "T3": "إلغاء",
	 "T4": "حفظ",
},
"bg_BG": {
	 "T1": "Използвайте UP и DOWN бутони за избор на вашия език. След това натиснете ОК",
	 "T2": "Избор Език",
	 "T3": "Отказ",
	 "T4": "Запази",
},
"nb_NO": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "Language selection",
	 "T3": "Cancel",
	 "T4": "Save",
},
"ca_AD": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "Selecció d'idioma",
	 "T3": "Cancel·lar",
	 "T4": "Save",
},
"cs_CZ": {
	 "T1": "Použijte tlačítka Nahoru a Dolů k výběru Vašeho jazyka. Poté stiskněte OK.",
	 "T2": "Výběr jazyka",
	 "T3": "Zavřít",
	 "T4": "Uložit",
},
"da_DK": {
	 "T1": "Benyt venligst OP og NED tasten til at vælge sprog. Tryk bagefter på OK knappen.",
	 "T2": "Valg af sprog",
	 "T3": "Fortryd",
	 "T4": "Gem",
},
"el_GR": {
	 "T1": "Χρησιμοποιήστε τα πλήκτρα ΠΑΝΩ και ΚΑΤΩ για επιλογή γλώσσας. Μετά πιέστε το ΟΚ.",
	 "T2": "Επιλογή γλώσσας",
	 "T3": "Άκυρο ",
	 "T4": "Αποθήκευση",
},
"en_GB": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "Language selection",
	 "T3": "Cancel",
	 "T4": "Save",
},
"en_US": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "Language selection",
	 "T3": "Cancel",
	 "T4": "Save",
},
"es_ES": {
	 "T1": "Usa las teclas ARRIBA y ABAJO para seleccionar el idioma. Después, pulsa el botón OK.",
	 "T2": "Selección de idioma",
	 "T3": "Cancelar",
	 "T4": "Guardar",
},
"et_EE": {
	 "T1": "Kasuta keele valimiseks 'ÜLES' ja 'ALLA' nuppe, seejärel vajuta OK.",
	 "T2": "Keele valik",
	 "T3": "Tühista",
	 "T4": "Salvesta",
},
"fa_IR": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "انتخاب زبان",
	 "T3": "انصراف",
	 "T4": "ذخیره",
},
"fi_FI": {
	 "T1": "Valitse kieli ylös/alas näppäimillä ja paina OK-näppäintä.",
	 "T2": "Kielivalinta",
	 "T3": "Peruuta",
	 "T4": "Tallenna",
},
"fr_FR": {
	 "T1": "Veuillez utiliser les touches HAUT et BAS pour choisir votre langue. Ensuite pressez le bouton OK.",
	 "T2": "Sélection de la langue",
	 "T3": "Annuler",
	 "T4": "Sauver",
},
"fy_NL": {
	 "T1": "Brúk de op en del toets om jo taal te kiezen. Dernei druk op OK",
	 "T2": "Taal Kieze",
	 "T3": "Ôfbrekke",
	 "T4": "Opslaan",
},
"he_IL": {
	 "T1": ".אנא בחר את השפה, לאחר מכן לחץ על אשר",
	 "T2": "בחירת שפה",
	 "T3": "בטל",
	 "T4": "שמור",
},
"hr_HR": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "Odaberite Jezik",
	 "T3": "Odustani",
	 "T4": "Save",
},
"hu_HU": {
	 "T1": "Kérem, használja a FEL és LE gombokat a nyelv kiválasztásához. Ez után nyomja le az OK gombot.",
	 "T2": "Nyelvválasztás",
	 "T3": "Mégse",
	 "T4": "Mentés",
},
"is_IS": {
	 "T1": "Vinsamlega notið UP og NIÐUR takka til að velja tungumál. Ýttu svo á OK til að nota.",
	 "T2": "Val tungumáls",
	 "T3": "Hætta við",
	 "T4": "Vista",
},
"it_IT": {
	 "T1": "Selezionare la propria lingua utilizzando i tasti Sù/Giù. Premere OK per confermare.",
	 "T2": "Selezione lingua",
	 "T3": "Annull.",
	 "T4": "Salvare",
},
"ku_KU": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "Language selection",
	 "T3": "Berdi",
	 "T4": "Save",
},
"lt_LT": {
	 "T1": "Prašome naudoti AUKŠTYN IR ŽEMYN mygtukus, kad išsirinktumėte savo kalbą. Po to spauskite OK mygtuką.",
	 "T2": "Kalbos pasirinkimas",
	 "T3": "Atšaukti",
	 "T4": "Saugoti",
},
"lv_LV": {
	 "T1": "Lūdzu lietojiet UP un DOWN taustiņus, lai izvēlētos valodu. Pēc tam spiediet OK.",
	 "T2": "Valodas izvēle",
	 "T3": "Atcelt",
	 "T4": "Saglabāt",
},
"nl_NL": {
	 "T1": "Gebruik de omhoog/omlaag toetsen om de gewenste taal te selecteren. Druk daarna op OK.",
	 "T2": "Taalkeuze",
	 "T3": "Annuleren",
	 "T4": "Opslaan",
},
"nb_NO": {
	 "T1": "Please use the UP and DOWN keys to select your language. Afterwards press the OK button.",
	 "T2": "Language selection",
	 "T3": "Cancel",
	 "T4": "Save",
},
"no_NO": {
	 "T1": "Vennligst bruk OPP og NED tastene for å velge ditt språk. Deretter trykk OK.",
	 "T2": "Språkvalg",
	 "T3": "Avbryte",
	 "T4": "Lagre",
},
"pl_PL": {
	 "T1": "W celu wyboru języka użyj klawiszy GÓRA i DÓŁ. Nastepnie nacisnij przycisk OK.",
	 "T2": "Wybór języka",
	 "T3": "Anuluj",
	 "T4": "Zapisz",
},
"pt_PT": {
	 "T1": "Por favor use as teclas de Cima e Baixi para selecionar a sua língua. Depois prima OK.",
	 "T2": "Selecção do Idioma",
	 "T3": "Cancelar",
	 "T4": "Guardar",
},
"pt_BR": {
	 "T1": "Use a tecla de cima ou de baixo para selecionar seu idioma. Depois pressione 'OK'.",
	 "T2": "Seleção do idioma",
	 "T3": "Cancelar",
	 "T4": "Guardar",
},
"ro_RO": {
	 "T1": "Va rugam folositi tastele SUS si JOS pentru a selecta limba. Dupa aceea apasatitasta OK.",
	 "T2": "Selectare limba",
	 "T3": "Anuleaza",
	 "T4": "Salvare",
},
"ru_RU": {
	 "T1": "Пожалуйста, используйте кнопки ВВЕРХ и ВНИЗ для выбора языка. Далее нажмите ОК.",
	 "T2": "Выбор языка",
	 "T3": "Отмена",
	 "T4": "Сохранить",
},
"sk_SK": {
	 "T1": "Tlačidlami NAHOR alebo NADOL zvoľte jazyk. Potom stlačte tlačidlo OK.",
	 "T2": "Voľba jazyka",
	 "T3": "Zrušiť",
	 "T4": "Uložiť",
},
"sl_SI": {
	 "T1": "Prosim, da za izbiro jezika uporabite tipke GOR in DOL. Za potrditev pritisnite OK tipko .",
	 "T2": "Izbira jezik",
	 "T3": "Izhod",
	 "T4": "Potrditev",
},
"sr_YU": {
	 "T1": "Molim koristite UP i DOWN tipke da izaberete jezik.Posle toga pritisnite OK dugme.",
	 "T2": "Izbor jezika",
	 "T3": "Odustani",
	 "T4": "Sačuvajte",
},
"sv_SE": {
	 "T1": "Vänligen använd UPP och NER pil för att välja språk. Efter val tryck på OK knappen.",
	 "T2": "Välj språk",
	 "T3": "Avbryt",
	 "T4": "Spara",
},
"th_TH": {
	 "T1": "ใช้ปุ่มขึ้นหรือลงเพื่อเลือกภาษาที่ต้องการ จากนั้นให้กดปุ่ม OK เพื่อเลือก",
	 "T2": "เลือกภาษา",
	 "T3": "ยกเลิก",
	 "T4": "บันทึก",
},
"tr_TR": {
	 "T1": "Lütfen dil seçiminizi yapmak için YUKARI ve AŞAĞI tuşlarını kullanın, sonrasında OK'a basın.",
	 "T2": "Dil seçimi",
	 "T3": "İptal",
	 "T4": "Kaydet",
},
"uk_UA": {
	 "T1": "Використовуйте кнопки ВВЕРХ і ВНИЗ, щоб вибрати Вашу мову. Після вибору натисніть OK.",
	 "T2": "Вибір мови",
	 "T3": "Відмінити",
	 "T4": "Зберегти",
},
}
